#!/bin/sh

case "$BLOCK_BUTTON" in
6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

read cpu a b c previdle rest </proc/stat
prevtotal=$((a + b + c + previdle))
sleep 0.5
read cpu a b c idle rest </proc/stat
total=$((a + b + c + idle))
cpu=$((100 * ((total - prevtotal) - (idle - previdle)) / (total - prevtotal)))
echo -e "󰻠 $cpu%"
